# Generated by Django 3.0 on 2022-04-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20220421_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lessons_completed',
        ),
    ]
