# Generated by Django 3.0 on 2022-04-22 13:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_student_lessons_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lessons_completed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), blank=True, default=list, size=None),
        ),
    ]
