# Generated by Django 3.0 on 2022-05-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_student_attempted_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='correct',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
