# Generated by Django 3.0 on 2022-05-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_student_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='problem_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
